name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 0 * * 0"


jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sponsorblockcast-docker:latest
